### ISSUE TITLE
编译失败

### ISSUE THREAD

**Issue by mybee** [bitleak/kvrocks#121]
Centos7

[root@i-h60b6jz2 kvrocks]# make -j4
cd src && make all
make[1]: 进入目录“/root/kvrocks/src”
    CC main.o
    CC server.o
    LINK kvrocks
/root/kvrocks/external/glog/.libs/libglog.a(libglog_la-logging.o)：在函数‘__static_initialization_and_destruction_0(int, int)’中：
logging.cc:(.text+0x6299)：对‘google::FlagRegisterer::FlagRegisterer(char const*, char const*, char const*, char const*, void*, void*)’未定义的引用
logging.cc:(.text+0x634b)：对‘google::FlagRegisterer::FlagRegisterer(char const*, char const*, char const*, char const*, void*, void*)’未定义的引用
logging.cc:(.text+0x63f5)：对‘google::FlagRegisterer::FlagRegisterer(char const*, char const*, char const*, char const*, void*, void*)’未定义的引用
logging.cc:(.text+0x649f)：对‘google::FlagRegisterer::FlagRegisterer(char const*, char const*, char const*, char const*, void*, void*)’未定义的引用
logging.cc:(.text+0x64dc)：对‘google::FlagRegisterer::FlagRegisterer(char const*, char const*, char const*, char const*, void*, void*)’未定义的引用
/root/kvrocks/external/glog/.libs/libglog.a(libglog_la-logging.o):logging.cc:(.text+0x657e): more undefined references to `google::FlagRegisterer::FlagRegisterer(char const*, char const*, char const*, char const*, void*, void*)' follow
collect2: 错误：ld 返回 1
make[1]: *** [kvrocks] 错误 1
make[1]: 离开目录“/root/kvrocks/src”
make: *** [all] 错误 2

**Comment by git-hulk** [comment]
@mybee 这个是因为你本地装了 gflags, 然后 glogs 自动识别加上了。可以先通过 make LDFLAGS+='-lgflags -pthread' 解决，我后面也在 makefile 里面去加一下 gflags

**Comment by mybee** [comment]
[root@i-h60b6jz2 kvrocks]# make LDFLAGS+='-lgflags -pthread'
cd src && make all
make[1]: 进入目录“/root/kvrocks/src”
    CC server.o
    CC main.o
    LINK kvrocks
/root/kvrocks/external/rocksdb/librocksdb.a(format.o)：在函数‘Snappy_GetUncompressedLength’中：
/root/kvrocks/external/rocksdb/./util/compression.h:563：对‘snappy::GetUncompressedLength(char const*, unsigned long, unsigned long*)’未定义的引用
/root/kvrocks/external/rocksdb/librocksdb.a(format.o)：在函数‘Snappy_Uncompress’中：
/root/kvrocks/external/rocksdb/./util/compression.h:574：对‘snappy::RawUncompress(char const*, unsigned long, char*)’未定义的引用
/root/kvrocks/external/rocksdb/librocksdb.a(block_based_table_builder.o)：在函数‘Snappy_Compress’中：
/root/kvrocks/external/rocksdb/./util/compression.h:547：对‘snappy::MaxCompressedLength(unsigned long)’未定义的引用
/root/kvrocks/external/rocksdb/./util/compression.h:549：对‘snappy::RawCompress(char const*, unsigned long, char*, unsigned long*)’未定义的引用
/root/kvrocks/external/glog/.libs/libglog.a(libglog_la-logging.o)：在函数‘__static_initialization_and_destruction_0(int, int)’中：
logging.cc:(.text+0x6299)：对‘google::FlagRegisterer::FlagRegisterer(char const*, char const*, char const*, char const*, void*, void*)’未定义的引用
logging.cc:(.text+0x634b)：对‘google::FlagRegisterer::FlagRegisterer(char const*, char const*, char const*, char const*, void*, void*)’未定义的引用
logging.cc:(.text+0x63f5)：对‘google::FlagRegisterer::FlagRegisterer(char const*, char const*, char const*, char const*, void*, void*)’未定义的引用
logging.cc:(.text+0x649f)：对‘google::FlagRegisterer::FlagRegisterer(char const*, char const*, char const*, char const*, void*, void*)’未定义的引用
logging.cc:(.text+0x64dc)：对‘google::FlagRegisterer::FlagRegisterer(char const*, char const*, char const*, char const*, void*, void*)’未定义的引用
/root/kvrocks/external/glog/.libs/libglog.a(libglog_la-logging.o):logging.cc:(.text+0x657e): more undefined references to `google::FlagRegisterer::FlagRegisterer(char const*, char const*, char const*, char const*, void*, void*)' follow
collect2: 错误：ld 返回 1
make[1]: *** [kvrocks] 错误 1
make[1]: 离开目录“/root/kvrocks/src”
make: *** [all] 错误 2




使用之后还是报一样的错...

**Comment by git-hulk** [comment]
咦，你是什么 os,  再试一下 make LDFLAGS+='-lsnappy -lgflags -pthread' ，另外确认一下本地是否安装了 snappy/gflags

**Comment by mybee** [comment]
1. CentOS7  
2. 这个命令也是同样的错
3. 有安装, 之前编译rocksdb装的
![image](https://user-images.githubusercontent.com/8556916/91267004-f50acd00-e7a4-11ea-8130-9f7612d53210.png)

**Comment by git-hulk** [comment]
你微信加一下我，搜索 hulkdev
