### ISSUE TITLE
kvrocks2redis works weird

### ISSUE THREAD

**Issue by winterfall233** [bitleak/kvrocks#145]
[What did I do?]
When I use kvrocks2redis to migrate data to a Redis server, the auth part does not work.
1.kvrocks server configured by:
    requirepass=mypwd_kvrocks
    # masterauth 
2.kvrocks2redis configured by:
    kvrocks xx.xx.xx.xx 6666 mypwd_kvrocks
    namespace.ns1 xx.xx.xx.xx 6379 mypwd_redis 1

Meanwhile, Redis server is ready with port 6379 & pwd 'mypwd_redis'.
And I did this on kvrocks server:
    ./redis-cli -h xx.xx.xx.xx -p 6666 -a mypwd_kvrocks namespace add ns1 mypwd_ns1
    ./redis-cli -h xx.xx.xx.xx -p 6666 -a mypwd_ns1 set key1 abcdefg
    ./redis-cli -h xx.xx.xx.xx -p 6666 -a mypwd_ns1 lpush key2 a b c

[ERROR LOG]
E1221 16:13:32.715910 99362 sync.cc:58] auth got invalid response
E1221 16:13:32.717257 99427 redis_writer.cc:90] [kvrocks2redis] redis select db failed: -NOAUTH Authentication required.
E1221 16:13:32.718616 99427 redis_writer.cc:90] [kvrocks2redis] redis select db failed: -NOAUTH Authentication required.
E1221 16:13:32.719998 99427 redis_writer.cc:90] [kvrocks2redis] redis select db failed: -NOAUTH Authentication required.
E1221 16:13:32.721364 99427 redis_writer.cc:90] [kvrocks2redis] redis select db failed: -NOAUTH Authentication required.
E1221 16:13:32.722718 99427 redis_writer.cc:90] [kvrocks2redis] redis select db failed: -NOAUTH Authentication required.
E1221 16:13:32.724040 99427 redis_writer.cc:90] [kvrocks2redis] redis select db failed: -NOAUTH Authentication required.
E1221 16:13:32.725356 99427 redis_writer.cc:90] [kvrocks2redis] redis select db failed: -NOAUTH Authentication required.

[Question~]
Am I doing the right config for kvrocks & kvrocks2redis? Why migration cannot work and log shows err in AUTH?

**Comment by git-hulk** [comment]
can u help to check this issue?

**Comment by winterfall233** [comment]
some guess: 
kvrocks2redis must config a "kvrocks slave node" as data source, right?

**Comment by karelrooted** [comment]
> some guess:
> kvrocks2redis must config "an existing kvrocks slave node" as data source, right?

is a bug, forgot to test password not empty situation after add selectDB support
