### ISSUE TITLE
Can I upgrade from 1.1.38 to 1.2.0

### ISSUE THREAD

**Issue by clyang** [bitleak/kvrocks#151]
According to the Changelog, rocksdb has been revert to previous version in 1.2.0.
Will it break anything if I upgrade from 1.1.38?

**Comment by git-hulk** [comment]
yup, the minor version wouldn't have the breaking change, so it's ok to upgrade the 1.1.x to the latest.

**Comment by clyang** [comment]
Got it. Many thanks!
