### ISSUE TITLE
QPS测试对比PIKA

### ISSUE THREAD

**Issue by smartlee** [bitleak/kvrocks#57]
对比了下和pika的性能测试，以下面的SET命令为例，不挂slave
```
redis-benchmark -t set -n 100000 -r 100000 -d 102400 -h host -p port
```
pika大概QPS稳定在2000+,kvrocks的大概900多，想请教是否有性能编译方面的优化建议以达到和pika差不多的性能？

**Comment by git-hulk** [comment]
这个不太应该，我之前测试数据来看性能是差不多。你看看配置的worker 线程数是否一直，kvrocks 默认只有 4

**Comment by smartlee** [comment]
> 这个不太应该，我之前测试数据来看性能是差不多。你看看配置的worker 线程数是否一直，kvrocks 默认只有 4

上面这个命令   你那边得到的QPS 是多少？我这边测试的机器也是E5的CPU kvrocks.conf里面配置worker的数量是8
