### ISSUE TITLE
slaveof redis的支持

### ISSUE THREAD

**Issue by smartlee** [bitleak/kvrocks#63]
因为我们实际业务需要，要支持kvrocks slaveof redis实例，目前这部分代码我已经实现了个最短路径：
* 支持redis的psync协议
* 解析redis的rdb文件
* 将rdb文件同步到kvrocks中
* 定期replconf ack offset
代码已经在测试环境跑通，当然距离真正上线还有断时间，此外redis slaveof kvrocks也在下步计划中想知道完善后是否可以将这部分代码提到到本仓库？因为可能有其他公司有类似的需求。

**Comment by git-hulk** [comment]
欢迎，这两个东西建议拆分提
