### ISSUE TITLE
build error with master

### ISSUE THREAD

**Issue by tkram01** [bitleak/kvrocks#81]
Hi,

I'm getting the following build error when trying to build from git.

[ 87%] Building CXX object CMakeFiles/kvrocks2redis.dir/tools/kvrocks2redis/parser.cc.o
[ 88%] Linking CXX executable kvrocks2redis
/usr/bin/ld: cannot find -lstdc++
collect2: error: ld returned 1 exit status
make[2]: *** [kvrocks2redis] Error 1
make[1]: *** [CMakeFiles/kvrocks2redis.dir/all] Error 2
make: *** [all] Error 2

 - OS: Red Hat Enterprise Linux Server release 7.2 (Maipo)

**To Reproduce**
1. sh build.sh build

**Comment by git-hulk** [comment]
It seems that libstdc++ wasn't installed, you can try:

```shell
sudo yum install libstdc++
sudo yum install libstdc++-devel
sudo yum install libstdc++-static
```

or use `sudo yum search libstdc++` to to see the matching packages

**Comment by tkram01** [comment]
this is what is installed

rpm -q -a | grep libstd

libstdc++-devel-4.8.5-4.el7.x86_64
libstdc++-4.8.5-4.el7.x86_64

**Comment by git-hulk** [comment]
@tkram01 by the way, you should use the Makefile instead of build.sh

```
# install the snappy first
$ sudo yum install -y snappy snappy-devel  
$ make -j4
```

**Comment by git-hulk** [comment]
> this is what is installed
> 
> rpm -q -a | grep libstd
> 
> libstdc++-devel-4.8.5-4.el7.x86_64
> libstdc++-4.8.5-4.el7.x86_64

you can try to fix it by installing the libstdc++-static package as well

**Comment by tkram01** [comment]
When using the Makefile I get

[appsuser@xxx kvrocks]$ make
cd src && make all
You need to run this command from the toplevel of the working tree.
make[1]: Entering directory `/apps/appsuser/kvrocks/src'

Hint: Fetching submodules from the remote
git submodule init
You need to run this command from the toplevel of the working tree.
make[1]: *** [SUBMODULES] Error 1
make[1]: Leaving directory `/apps/appsuser/kvrocks/src'
make: *** [all] Error 2

**Comment by git-hulk** [comment]
> You need to run this command from the toplevel of the working tree.

you should run the `make` command from toplevel of the working tree instead of src

**Comment by tkram01** [comment]
I did...

[appsuser@xxx kvrocks]$ pwd
/cluster/home/appsuser/kvrocks
[appsuser@xxx kvrocks]$ make
cd src && make all
You need to run this command from the toplevel of the working tree.
make[1]: Entering directory `/apps/appsuser/kvrocks/src'

Hint: Fetching submodules from the remote
git submodule init
You need to run this command from the toplevel of the working tree.
make[1]: *** [SUBMODULES] Error 1
make[1]: Leaving directory `/apps/appsuser/kvrocks/src'
make: *** [all] Error 2

**Comment by git-hulk** [comment]
It seems that working dir didn't work in Redhat, you can replace the `src/Makefile` line 12:

```
clone_dependencies := $(shell sh -c 'git submodule init && git submodule update')
```
with
```
clone_dependencies := $(shell sh -c 'cd .. && git submodule init && git submodule update && cd src')
```

or execute the command manually
```
git submodule init && git submodule update
```

**Comment by tkram01** [comment]
working now - thanks!
